### ISSUE TITLE
ERROR -- : Bad file descriptor (Errno::EBADF)

### ISSUE THREAD

**Issue by kirantpatil** [mirasrael/daemons-rails#27]
I am getting below error when I start daemon as "rake daemon:park:start" also my source code snippet is attached below.

I am not getting any error when I run it in forground as below
[kpatil@dhcppc21 svg_nload]$ rake daemon:park

### [kpatil@dhcppc21 svg_nload]$ tail -100 log/park.rb.log 

[2015-06-19T11:31:28.804611 #4047] ERROR -- : Bad file descriptor (Errno::EBADF)
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons/daemonize.rb:133:in `for_fd'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons/daemonize.rb:133:in `block in close_io'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons/daemonize.rb:132:in `upto'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons/daemonize.rb:132:in `close_io'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons/daemonize.rb:110:in `daemonize'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons/application.rb:162:in `start_load'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons/application.rb:297:in `start'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons/controller.rb:56:in `run'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons.rb:144:in `block in run'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `call'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `catch_exceptions'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons.rb:143:in `run'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/park_ctl:6:in `<main>'
E, [2015-06-19T11:31:28.804674 #4047] ERROR -- : Bad file descriptor (Errno::EBADF)

### [kpatil@dhcppc21 svg_nload]$ vi lib/daemons/park.rb 
#!/usr/bin/env ruby
require 'socket'               # Get sockets from stdlib
require 'parkmgmt/udpserver'
...
....
\# Replace this with your code

  server = ParkServ::UDPServer.new(2000)
  server.start

### [kpatil@dhcppc21 svg_nload]$ vi lib/parkmgmt/udpserver.rb 
require 'socket'

module ParkServ
  class UDPServer
    def initialize(port)
      @port = port
    end

    def start
      @socket = UDPSocket.new
      @socket.bind("", @port) # is nil OK here?
      while true
          handle(@socket)
      end
    end

    def handle(socket)
          puts "I am here"
    end
  end
end

**Comment by kirantpatil** [comment]
The daemon process starts if I copy the udpserver.rb code in to park.rb file.

I purposefully kept server code in lib directory for modularity.

So, what should I do now ?

**Comment by kirantpatil** [comment]
closing this since I placed the entire code under park.rb file which works perfectly.
